version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=remix
      - POSTGRES_PASSWORD=password1
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres-db:
    driver: local
